/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.AksesAdmin;

/**
 *
 * @author ASUS
 */
public class AboutPageView extends javax.swing.JFrame {

    private String username;

    public AboutPageView(String username) {
        this.username = username;
        initComponents();
        aboutLabel.setText(
                "<html>SIANIDA (Sistem Informasi Andalan Dunia Literasi) adalah sebuah platform digital "
                + "yang dirancang untuk menjadi pusat informasi, kolaborasi, dan pengembangan dunia <br>literasi."
                + "Kami percaya bahwa literasi bukan sekadar kemampuan membaca dan <br>menulis,tetapi juga kunci "
                + "untuk membangun masyarakat yang kritis, kreatif, dan melek informasi.<br><br>"
                + "Melalui SIANIDA, kami menghadirkan ruang terbuka bagi pembaca, penulis, pengajar, serta "
                + "pegiat literasi untuk saling berbagi pengetahuan, karya, dan inspirasi. Mulai dari artikel "
                + "edukatif, ulasan buku, hingga wadah diskusi literasi—semuanya tersedia dalam satu sistem yang "
                + "mudah diakses dan ramah pengguna.<br><br>"
                + "Fitur Admin:<br>"
                + "1. Pinjam Buku <br>"
                + "2. Buku Saya<br>"
                + "3. Pengembalian Buku<br>"
                + "4. Akun Saya<br></html>"
        );

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        aboutLabel = new javax.swing.JLabel();
        linkIGAdi = new javax.swing.JLabel();
        linkIGReza = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        waAdi = new javax.swing.JLabel();
        waReza = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(200, 172, 144));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(150, 99, 31));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
        });
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/gambarTambahBukuIcons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel6.setText("Back");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 110, 40));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("4) XAMPP");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 340, -1));

        jPanel4.setBackground(new java.awt.Color(95, 70, 38));
        jPanel4.setForeground(new java.awt.Color(95, 70, 38));
        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 150, 5));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(95, 70, 38));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/gambarTambahBukuIcons/icons8-tools-50 (1).png"))); // NOI18N
        jLabel3.setText(" Tools");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 160, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("1) Apache Netbeans");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 340, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("2) Java Programming");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 340, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("3) MySQL");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 340, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("© copyright | SIANIDA");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 690, 240, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 720));

        jPanel2.setBackground(new java.awt.Color(239, 233, 226));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(150, 99, 31));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("X");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 30, 40));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 80, 40));

        jPanel3.setBackground(new java.awt.Color(136, 107, 70));
        jPanel3.setForeground(new java.awt.Color(136, 107, 70));
        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 345, 5));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(136, 107, 70));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/gambarTambahBukuIcons/icons8-library-64 (1).png"))); // NOI18N
        jLabel2.setText("Tentang SIANIDA");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 340, -1));

        jPanel5.setBackground(new java.awt.Color(239, 233, 226));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(179, 141, 97)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        aboutLabel.setBackground(new java.awt.Color(239, 233, 226));
        aboutLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aboutLabel.setForeground(new java.awt.Color(0, 0, 0));
        aboutLabel.setText("jLabel10");
        aboutLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel5.add(aboutLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 720, 420));

        linkIGAdi.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        linkIGAdi.setForeground(new java.awt.Color(51, 153, 255));
        linkIGAdi.setText("@adi.stya_");
        linkIGAdi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkIGAdiMouseClicked(evt);
            }
        });
        jPanel5.add(linkIGAdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 510, 130, 30));

        linkIGReza.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        linkIGReza.setForeground(new java.awt.Color(51, 153, 255));
        linkIGReza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/gambarTambahBukuIcons/icons8-instagram-48.png"))); // NOI18N
        linkIGReza.setText("@_rerap");
        linkIGReza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkIGRezaMouseClicked(evt);
            }
        });
        jPanel5.add(linkIGReza, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 150, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Hubungi Kami:");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 150, 30));

        waAdi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        waAdi.setForeground(new java.awt.Color(136, 107, 70));
        waAdi.setText("088221135296 (Adi)");
        waAdi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                waAdiMouseClicked(evt);
            }
        });
        jPanel5.add(waAdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 510, 250, 40));

        waReza.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        waReza.setForeground(new java.awt.Color(136, 107, 70));
        waReza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/gambarTambahBukuIcons/icons8-whatsapp-48.png"))); // NOI18N
        waReza.setText("081227213841 (Reza)");
        waReza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                waRezaMouseClicked(evt);
            }
        });
        jPanel5.add(waReza, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, 250, 40));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 760, 550));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 840, 720));

        setSize(new java.awt.Dimension(1200, 720));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel8MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        HomePageAdminView homepage = new HomePageAdminView(username);
        homepage.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void linkIGRezaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkIGRezaMouseClicked
        try {
            java.awt.Desktop.getDesktop().browse(new java.net.URI("https://instagram.com/_rerap"));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_linkIGRezaMouseClicked

    private void linkIGAdiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkIGAdiMouseClicked
        try {
            java.awt.Desktop.getDesktop().browse(new java.net.URI("https://instagram.com/adi.stya_"));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_linkIGAdiMouseClicked

    private void waAdiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_waAdiMouseClicked
        try {
            java.awt.Desktop.getDesktop().browse(new java.net.URI("https://wa.me/088221135296"));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_waAdiMouseClicked

    private void waRezaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_waRezaMouseClicked
        try {
            java.awt.Desktop.getDesktop().browse(new java.net.URI("https://wa.me/6281227213841"));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_waRezaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AboutPageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AboutPageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AboutPageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AboutPageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AboutPageView("Admin").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aboutLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel linkIGAdi;
    private javax.swing.JLabel linkIGReza;
    private javax.swing.JLabel waAdi;
    private javax.swing.JLabel waReza;
    // End of variables declaration//GEN-END:variables
}
