/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.AksesAdmin;

import Controller.ManajemenPenggunaController;
import Model.User.User;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author ASUS
 */
public class ManajemenPenggunaView extends javax.swing.JFrame {

    private String username;
    DefaultTableModel model;
    ManajemenPenggunaController controller;

    public ManajemenPenggunaView(String username) {
        this.username = username;
        initComponents();
        controller = new ManajemenPenggunaController(this, username);
        controller.loadTable();

    }

    public DefaultTableModel getTblModel() {
        return (DefaultTableModel) tbl_detailPengguna.getModel();
    }

    public void showMessage(String msg) {
        JOptionPane.showMessageDialog(this, msg);
    }

    public void showError(String msg) {
        JOptionPane.showMessageDialog(this, msg, "Error", JOptionPane.ERROR_MESSAGE);
    }
    public void showWarning(String msg, String title) {
        JOptionPane.showMessageDialog(this, msg, title, JOptionPane.WARNING_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        text_Nama = new app.bolivia.swing.JCTextField();
        HapusUser = new rojeru_san.complementos.RSButtonHover();
        TambahPengguna = new rojeru_san.complementos.RSButtonHover();
        EditUser = new rojeru_san.complementos.RSButtonHover();
        text_Email = new app.bolivia.swing.JCTextField();
        text_Telp = new app.bolivia.swing.JCTextField();
        text_idUser = new app.bolivia.swing.JCTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_detailPengguna = new rojeru_san.complementos.RSTableMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(200, 172, 144));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(150, 99, 31));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(150, 99, 31));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/gambarTambahBukuIcons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel3.setText("Back");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 110, 40));

        jPanel6.setBackground(new java.awt.Color(150, 99, 31));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/gambarTambahBukuIcons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel4.setText("Back");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 110, 40));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 40));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 40));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/gambarTambahBukuIcons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel5.setText("Back");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 110, 40));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 40));

        jLabel9.setBackground(new java.awt.Color(240, 240, 240));
        jLabel9.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/gambarTambahBukuIcons/icons8_Contact_26px.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 40, 50));

        jLabel13.setBackground(new java.awt.Color(240, 240, 240));
        jLabel13.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("ID Pengguna");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 110, 20));

        jLabel10.setBackground(new java.awt.Color(240, 240, 240));
        jLabel10.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/gambarTambahBukuIcons/icons8_Collaborator_Male_26px.png"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 40, 50));

        jLabel14.setBackground(new java.awt.Color(240, 240, 240));
        jLabel14.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Nama Pengguna");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 130, 20));

        jLabel11.setBackground(new java.awt.Color(240, 240, 240));
        jLabel11.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/gambarIcons/icon8-mail-24.png"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 30, 40));

        jLabel15.setBackground(new java.awt.Color(240, 240, 240));
        jLabel15.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Email");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 110, 20));

        jLabel12.setBackground(new java.awt.Color(240, 240, 240));
        jLabel12.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/gambarTambahBukuIcons/icons8_Unit_26px.png"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 40, 50));

        jLabel16.setBackground(new java.awt.Color(240, 240, 240));
        jLabel16.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("No Telepon");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 120, 20));

        text_Nama.setBackground(new java.awt.Color(200, 172, 144));
        text_Nama.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        text_Nama.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        text_Nama.setPlaceholder("Masukkan Nama...");
        text_Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_NamaActionPerformed(evt);
            }
        });
        jPanel2.add(text_Nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 260, -1));

        HapusUser.setBackground(new java.awt.Color(255, 0, 0));
        HapusUser.setText("Hapus User");
        HapusUser.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        HapusUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusUserActionPerformed(evt);
            }
        });
        jPanel2.add(HapusUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, 310, -1));

        TambahPengguna.setBackground(new java.awt.Color(22, 206, 12));
        TambahPengguna.setText("Tambah User");
        TambahPengguna.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TambahPengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahPenggunaActionPerformed(evt);
            }
        });
        jPanel2.add(TambahPengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 310, -1));

        EditUser.setText("Edit User");
        EditUser.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        EditUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditUserActionPerformed(evt);
            }
        });
        jPanel2.add(EditUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 310, -1));

        text_Email.setBackground(new java.awt.Color(200, 172, 144));
        text_Email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        text_Email.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        text_Email.setPlaceholder("Masukkan Email...");
        text_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_EmailActionPerformed(evt);
            }
        });
        jPanel2.add(text_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 260, -1));

        text_Telp.setBackground(new java.awt.Color(200, 172, 144));
        text_Telp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        text_Telp.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        text_Telp.setPlaceholder("Masukkan No Telepon...");
        text_Telp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_TelpActionPerformed(evt);
            }
        });
        jPanel2.add(text_Telp, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 260, -1));

        text_idUser.setBackground(new java.awt.Color(200, 172, 144));
        text_idUser.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        text_idUser.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        text_idUser.setPlaceholder("Masukkan ID...");
        jPanel2.add(text_idUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 260, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 720));

        jPanel5.setBackground(new java.awt.Color(239, 233, 226));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(150, 99, 31));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
        });
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        jPanel8.setBackground(new java.awt.Color(150, 99, 31));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel8.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 3, 30, 30));

        jPanel5.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 70, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(136, 107, 70));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/gambarIcons/icons8-user-50.png"))); // NOI18N
        jLabel1.setText("Manajemen Pengguna");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jPanel1.setBackground(new java.awt.Color(136, 107, 70));
        jPanel1.setForeground(new java.awt.Color(136, 107, 70));
        jPanel5.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 400, 5));

        tbl_detailPengguna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama ", "Email", "No Telepon"
            }
        ));
        tbl_detailPengguna.setColorBackgoundHead(new java.awt.Color(162, 132, 94));
        tbl_detailPengguna.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tbl_detailPengguna.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tbl_detailPengguna.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tbl_detailPengguna.setColorSelBackgound(new java.awt.Color(235, 206, 148));
        tbl_detailPengguna.setFont(new java.awt.Font("Yu Gothic Light", 0, 25)); // NOI18N
        tbl_detailPengguna.setFuenteFilas(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        tbl_detailPengguna.setFuenteFilasSelect(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        tbl_detailPengguna.setFuenteHead(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        tbl_detailPengguna.setRowHeight(40);
        tbl_detailPengguna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_detailPenggunaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_detailPengguna);
        if (tbl_detailPengguna.getColumnModel().getColumnCount() > 0) {
            tbl_detailPengguna.getColumnModel().getColumn(0).setMinWidth(65);
            tbl_detailPengguna.getColumnModel().getColumn(0).setMaxWidth(65);
        }

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 740, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 800, 720));

        setSize(new java.awt.Dimension(1200, 720));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked

    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel7MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        HomePageAdminView homepage = new HomePageAdminView(username);
        homepage.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked
    private void TambahPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahPenggunaActionPerformed
        try {
            int idBaru = Integer.parseInt(text_idUser.getText());
            String namaBaru = text_Nama.getText();
            String Email = text_Email.getText();
            String Telepon = text_Telp.getText();
            String password = "user123";
            int role = 2;

            User userBaru = new User(idBaru, namaBaru, password, Email, Telepon,role);
            userBaru.setidUser(idBaru);
            userBaru.setNamaPengguna(namaBaru);
            userBaru.setPasswordPengguna(password);
            userBaru.setEmail(Email);
            userBaru.setNomorTelepon(Telepon);
            userBaru.setIdRole(role);

            controller.addUser(userBaru);

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                    "Semua field wajib diisi dan sesuai dengan format",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_TambahPenggunaActionPerformed

    private void EditUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditUserActionPerformed
        if (text_idUser.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Silakan pilih baris terlebih dahulu.");
            return;
        }
        try {
            int idBaru = Integer.parseInt(text_idUser.getText());
            String namaBaru = text_Nama.getText();
            String Email = text_Email.getText();
            String Telepon = text_Telp.getText();

            User UserTerpilih = new User(idBaru, namaBaru, Email, Telepon);
            UserTerpilih.setidUser(idBaru);
            UserTerpilih.setNamaPengguna(namaBaru);
            UserTerpilih.setEmail(Email);
            UserTerpilih.setNomorTelepon(Telepon);

            controller.editUser(UserTerpilih);

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                    "Format angka salah: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_EditUserActionPerformed

    private void HapusUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusUserActionPerformed
        int rowNo = tbl_detailPengguna.getSelectedRow();
        if (rowNo == -1) {
            JOptionPane.showMessageDialog(this,
                    "Silakan pilih baris yang akan dihapus.",
                    "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int idForm = Integer.parseInt(text_idUser.getText());
        String namaForm = text_Nama.getText();
        String emailForm = text_Email.getText();
        String nomorTeleponForm = text_Telp.getText();

        User UserForm = new User(idForm, namaForm, emailForm, nomorTeleponForm);
        UserForm.setidUser(idForm);
        UserForm.setNamaPengguna(namaForm);
        UserForm.setEmail(emailForm);
        UserForm.setNomorTelepon(nomorTeleponForm);

        int konfirm = JOptionPane.showConfirmDialog(this,
                "Yakin ingin menghapus User \"" + namaForm + "\"?",
                "Konfirmasi Hapus",
                JOptionPane.YES_NO_OPTION);
        if (konfirm != JOptionPane.YES_OPTION) {
            return;
        }

        controller.deleteUser(UserForm);
    }//GEN-LAST:event_HapusUserActionPerformed

    private void text_NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_NamaActionPerformed

    private void tbl_detailPenggunaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_detailPenggunaMouseClicked
        int rowNo = tbl_detailPengguna.getSelectedRow();
        if (rowNo == -1) {
            return;
        }
        TableModel m = tbl_detailPengguna.getModel();

        text_idUser.setText(m.getValueAt(rowNo, 0).toString());
        text_Nama.setText(m.getValueAt(rowNo, 1).toString());
        text_Email.setText(m.getValueAt(rowNo, 2).toString());
        text_Telp.setText(m.getValueAt(rowNo, 3).toString());

        EditUser.setEnabled(true);
        HapusUser.setEnabled(true);
    }//GEN-LAST:event_tbl_detailPenggunaMouseClicked

    private void text_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_EmailActionPerformed

    private void text_TelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_TelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_TelpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManajemenPenggunaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManajemenPenggunaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManajemenPenggunaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManajemenPenggunaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManajemenPenggunaView("Guest").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.complementos.RSButtonHover EditUser;
    private rojeru_san.complementos.RSButtonHover HapusUser;
    private rojeru_san.complementos.RSButtonHover TambahPengguna;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private rojeru_san.complementos.RSTableMetro tbl_detailPengguna;
    private app.bolivia.swing.JCTextField text_Email;
    private app.bolivia.swing.JCTextField text_Nama;
    private app.bolivia.swing.JCTextField text_Telp;
    private app.bolivia.swing.JCTextField text_idUser;
    // End of variables declaration//GEN-END:variables
}
