package View.AksesAdmin;

import Controller.RekapPeminjamanController;
import com.raven.datechooser.SelectedDate;
import java.sql.Date;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author ASUS
 */
public class RekapPeminjamanView extends javax.swing.JFrame {

    private String username;
    private RekapPeminjamanController controller;

    public RekapPeminjamanView(String username) {
        this.username = username;
        initComponents();
        controller = new RekapPeminjamanController(this, username);
        controller.loadTableAll();
    }

    public DefaultTableModel getTblModel() {
        return (DefaultTableModel) tbl_detailBuku.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        datePinjam = new com.raven.datechooser.DateChooser();
        dateTempo = new com.raven.datechooser.DateChooser();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_detailBuku = new rojeru_san.complementos.RSTableMetro();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cariTanggal = new rojerusan.RSMaterialButtonCircle();
        tglPinjam = new app.bolivia.swing.JCTextField();
        buttonPinjam = new javax.swing.JButton();
        tglKembali = new app.bolivia.swing.JCTextField();
        buttonTempo = new javax.swing.JButton();

        datePinjam.setForeground(new java.awt.Color(82, 55, 29));
        datePinjam.setTextRefernce(tglPinjam);

        dateTempo.setForeground(new java.awt.Color(82, 55, 29));
        dateTempo.setTextRefernce(tglKembali);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(239, 233, 226));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_detailBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nama Buku", "Nama Peminjam", "Tanggal Pinjam", "Jatuh Tempo", "Pengembalian"
            }
        ));
        tbl_detailBuku.setColorBackgoundHead(new java.awt.Color(162, 132, 94));
        tbl_detailBuku.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tbl_detailBuku.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tbl_detailBuku.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tbl_detailBuku.setColorSelBackgound(new java.awt.Color(235, 206, 148));
        tbl_detailBuku.setFont(new java.awt.Font("Yu Gothic Light", 0, 25)); // NOI18N
        tbl_detailBuku.setFuenteFilas(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        tbl_detailBuku.setFuenteFilasSelect(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        tbl_detailBuku.setFuenteHead(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        tbl_detailBuku.setRowHeight(40);
        tbl_detailBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_detailBukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_detailBuku);
        if (tbl_detailBuku.getColumnModel().getColumnCount() > 0) {
            tbl_detailBuku.getColumnModel().getColumn(0).setMinWidth(70);
            tbl_detailBuku.getColumnModel().getColumn(0).setMaxWidth(70);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 1180, 370));

        jPanel3.setBackground(new java.awt.Color(200, 172, 144));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(150, 99, 31));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel8.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 30, 30));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("X");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel8.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 30, 30));

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 0, 70, 40));

        jPanel6.setBackground(new java.awt.Color(150, 99, 31));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/gambarTambahBukuIcons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel3.setText("Back");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 110, 40));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/gambarTambahBukuIcons/icons8_Literature_100px_1.png"))); // NOI18N
        jLabel1.setText("Rekap Peminjaman");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 480, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 400, 5));

        jLabel18.setBackground(new java.awt.Color(240, 240, 240));
        jLabel18.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Jatuh Tempo");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 130, 170, -1));

        jLabel19.setBackground(new java.awt.Color(240, 240, 240));
        jLabel19.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Tanggal Pinjam");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 170, 40));

        cariTanggal.setBackground(new java.awt.Color(162, 132, 94));
        cariTanggal.setText("Cari");
        cariTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariTanggalActionPerformed(evt);
            }
        });
        jPanel3.add(cariTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 210, 70));

        tglPinjam.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(82, 55, 29)));
        tglPinjam.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tglPinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tglPinjamMouseClicked(evt);
            }
        });
        tglPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglPinjamActionPerformed(evt);
            }
        });
        jPanel3.add(tglPinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 265, 40));

        buttonPinjam.setBackground(new java.awt.Color(82, 55, 29));
        buttonPinjam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/gambarTambahBukuIcons/icons8-calendar-32.png"))); // NOI18N
        buttonPinjam.setFocusable(false);
        buttonPinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonPinjamMouseClicked(evt);
            }
        });
        jPanel3.add(buttonPinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 155, 60, 50));

        tglKembali.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(82, 55, 29)));
        tglKembali.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tglKembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tglKembaliMouseClicked(evt);
            }
        });
        tglKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglKembaliActionPerformed(evt);
            }
        });
        jPanel3.add(tglKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 160, 265, 40));

        buttonTempo.setBackground(new java.awt.Color(82, 55, 29));
        buttonTempo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/gambarTambahBukuIcons/icons8-calendar-32.png"))); // NOI18N
        buttonTempo.setFocusable(false);
        buttonTempo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonTempoMouseClicked(evt);
            }
        });
        jPanel3.add(buttonTempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 155, 60, 50));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 280));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 720));

        setSize(new java.awt.Dimension(1200, 720));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        HomePageAdminView homepage = new HomePageAdminView(username);
        homepage.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void tbl_detailBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_detailBukuMouseClicked

    }//GEN-LAST:event_tbl_detailBukuMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void cariTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariTanggalActionPerformed
        SelectedDate utilD1 = datePinjam.getSelectedDate();
        SelectedDate utilD2 = dateTempo.getSelectedDate();
        if (utilD1 == null || utilD2 == null) {
            JOptionPane.showMessageDialog(this,
                    "Pilih tanggal pinjam dan tanggal kembali terlebih dahulu");
            return;
        }
        int tglP = utilD1.getDay();
        int bulanP = utilD1.getMonth() - 1;
        int tahunP = utilD1.getYear();
        int tglK = utilD2.getDay();
        int bulanK = utilD2.getMonth() - 1;
        int tahunK = utilD2.getYear();

        Calendar calendar = Calendar.getInstance();
        calendar.set(tahunP, bulanP, tglP);
        java.util.Date utilDate1 = calendar.getTime();
        Calendar cl = Calendar.getInstance();
        cl.set(tahunK, bulanK, tglK);
        java.util.Date utilDate2 = cl.getTime();

        java.sql.Date sqlFrom = new java.sql.Date(utilDate1.getTime());
        java.sql.Date sqlTo = new java.sql.Date(utilDate2.getTime());

        if (sqlTo.before(sqlFrom)) {
            JOptionPane.showMessageDialog(this,
                    "Tanggal jatuh tempo tidak boleh sebelum tanggal pinjam",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        controller.loadTableByDate(sqlFrom, sqlTo);
    }//GEN-LAST:event_cariTanggalActionPerformed

    private void tglPinjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tglPinjamMouseClicked
        datePinjam.showPopup();
    }//GEN-LAST:event_tglPinjamMouseClicked

    private void tglPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglPinjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglPinjamActionPerformed

    private void buttonPinjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPinjamMouseClicked
        datePinjam.showPopup();
    }//GEN-LAST:event_buttonPinjamMouseClicked

    private void tglKembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tglKembaliMouseClicked
        dateTempo.showPopup();
    }//GEN-LAST:event_tglKembaliMouseClicked

    private void tglKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglKembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglKembaliActionPerformed

    private void buttonTempoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonTempoMouseClicked
        dateTempo.showPopup();
    }//GEN-LAST:event_buttonTempoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RekapPeminjamanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RekapPeminjamanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RekapPeminjamanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RekapPeminjamanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RekapPeminjamanView("Guest").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonPinjam;
    private javax.swing.JButton buttonTempo;
    private rojerusan.RSMaterialButtonCircle cariTanggal;
    private com.raven.datechooser.DateChooser datePinjam;
    private com.raven.datechooser.DateChooser dateTempo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private rojeru_san.complementos.RSTableMetro tbl_detailBuku;
    private app.bolivia.swing.JCTextField tglKembali;
    private app.bolivia.swing.JCTextField tglPinjam;
    // End of variables declaration//GEN-END:variables
}
